#pipeline:
#  build:
#    image: maven:3.6-alpine
#    commands:
#      - mvn clean package -Dmaven.test.skip=true


kind: pipeline
name: default

steps:


  - name: deploy
    image: alpine:3.8
    commands:
      - ls /
    when:
      branch:
        - master


  - name: install
    image: alpine:3.8
    commands:
      - ls /dev
    when:
      branch:
        - dev
