
---
kind: pipeline
name: default


steps:
  - name: sync_push
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/enoa.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - push
    commands:
      - git remote add github $REPO_REMOTE
      - git push github $DRONE_BRANCH

  - name: sync_tag
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/enoa.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - tag
    commands:
      - git remote add github $REPO_REMOTE
      - git fetch origin
      - git push github $DRONE_TAG

volumes:
  - name: git_credentials
    host:
      path: /data/mount/git/.git-credentials
  - name: git_config
    host:
      path: /data/mount/git/.gitconfig



---
kind: pipeline
name: maven_center

steps:
  - name: deploy
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
      - name: gpg
        path: /root/.gnupg
    commands:
      - apk add gnupg
      - mvn clean deploy -Dmaven.test.skip=true -Prelease

volumes:
  - name: m2
    host:
      path: /data/mount/m2
  - name: gpg
    host:
      path: /data/gnupg

trigger:
  event:
    - tag

---
kind: pipeline
name: install_local

steps:
  - name: install
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
    commands:
      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

volumes:
  - name: m2
    host:
      path: /data/mount/m2

trigger:
  event:
    - push


#---
#kind: pipeline
#name: default
#
#steps:
#
#  ## xtodo deploy mode
#  - name: deploy
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean package -Dmaven.test.skip=true
#    when:
#      branch:
#        - master
#
#
#  - name: install
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
#    when:
#      branch:
#        - dev
#
#
#
#volumes:
#  - name: m2
#    host:
#      path: /data/mount/m2

